### ISSUE TITLE
Windows build problems

### ISSUE THREAD

**Issue by gkralik** [gkralik/php7-sapnwrfc#122]
I tried building with Visual Studio 2017, Visual Studio 2019, but it doesn't seems to work.
I've made a successful build on MacOS for PHP 8.0.12 but unable to make one on Windows.
Does anyone have a build for PHP 8.0 Thread Safe?

On MacOS, I needed the SAPRFCSDK PL6
On Windows we still need the SAPRFCSDK PL5 as in the lib folder there are no *.lib extensions only *.dylib

![IMG_0290](https://user-images.githubusercontent.com/5064872/139325822-8fc2ab60-e33b-4647-86bb-2543945b6515.jpg)

Here is my error:

```
Generating code
Finished generating code
exceptions.obj : error LNK2001: unresolved external symbol zend_string_init_interned
exceptions.obj : error LNK2001: unresolved external symbol spl_ce_RuntimeException
sapnwrfc.obj : error LNK2001: unresolved external symbol std_object_handlers
C:\php-sdk\phpdev\vs16\x64\php-8.0.12-src\x64\Release_TS\php_sapnwrfc.dll : fatal error LNK1120: 3 unresolved externals
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\link.exe"' : return code '0x460'
Stop.

c:\php-sdk\phpdev\vs16\x64\php-8.0.12-src
```

_Originally posted by @szabizs in https://github.com/gkralik/php7-sapnwrfc/issues/102#issuecomment-954151695_

**Comment by gkralik** [comment]
I have updated the [Windows build instructions](https://gkralik.github.io/php7-sapnwrfc/building.html#building-on-windows).
